import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Hero from '@/components/AboutUsPage/Hero'
import HeroImage from '@/components/AboutUsPage/HeroImage'
import PageMetric from '@/components/AboutUsPage/PageMetric'
import Header from '@/components/Header'
import Value from '@/components/AboutUsPage/Value'
import Team from '@/components/AboutUsPage/Team'
import Footer from '@/components/AboutUsPage/Footer'


function AboutUs() {
  return (
    <>
    <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex bg-[#f4f4f4] justify-center flex-col'>
      <Header />
      <Hero />
      <HeroImage />
      <PageMetric />
      <Value />
      <Team />
      <Footer />
      </main>
    </>
  )
}

export default AboutUs
