import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect} from 'react'

import Hero from '@/components/Hero'
import Section1 from '@/components/Section1'
import Section2 from '@/components/Section2'
import ReactPlayer from 'react-player/lazy'
import test from '@/assets/test'
import { motion } from 'framer-motion'
import Section3 from '@/components/Section3'
import Section4 from '@/components/Section4'
import Section5 from '@/components/Section5'
import Footer from '@/components/Footer'
import { Player } from '@lottiefiles/react-lottie-player'



export default function Home() {

  useEffect(() => {
    import ('@dotlottie/player-component')
  })

  return (
    <>
      <Head>
        <title>Beekreed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col bg-white'>
        <div className='w-[100%] border-b-2 fixed z-20 bg-white border-[#00000005]'>
       <div className='p-[1rem] w-[100%] flex justify-center items-center'>
       <h1 className='border-black font-sans font-semibold px-[1rem] border-[3px]'>Beekreed</h1>
       </div>
       
       </div>
       <Hero />
       <Section1 />
       <section className='h-[100vh] px-[5%] w-[100%] bg-black text-white flex items-center justify-center'>
       <div class="max-w-[85rem] px-4 py-10 sm:px-6 lg:px-8 lg:py-14 mx-auto">
  
  <div class="lg:grid lg:grid-cols-12 lg:gap-16 lg:items-center">
    <div class="lg:col-span-7">
      
      <div class="grid grid-cols-12 gap-2 sm:gap-6 items-center lg:-translate-x-10">
        <div class="col-span-4">
          <img class="" src="https://images.unsplash.com/photo-1606868306217-dbf5046868d2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1981&q=80" alt="Image Description" />
        </div>
     

        <div class="col-span-3">
          <img class="" src="https://images.unsplash.com/photo-1605629921711-2f6b00c6bbf4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80" alt="Image Description" />
        </div>
        

        <div class="col-span-5">
          <img class="" src="https://images.unsplash.com/photo-1600194992440-50b26e0a0309?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80" alt="Image Description" />
        </div>
        
      </div>
      
    </div>
  

    <div class="mt-5 sm:mt-10 lg:mt-0 lg:col-span-5">
      <div class="space-y-6 sm:space-y-8">
        
        <div class="space-y-2 md:space-y-4">
          <h2 class="font-sans font-bold text-3xl lg:text-4xl text-white">
            Collaborative tools to design user experience
          </h2>
          <p class="font-sans font-normal text-gray-500">
            Use our tools to explore your ideas and make your vision come true. Then share your work easily.
          </p>
        </div>
        
        <ul role="list" class="space-y-2 font-sans sm:space-y-4">
          <li class="flex space-x-3">
           
            <svg class="flex-shrink-0 h-6 w-6 text-purple-600 dark:text-blue-500" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M15.1965 7.85999C15.1965 3.71785 11.8387 0.359985 7.69653 0.359985C3.5544 0.359985 0.196533 3.71785 0.196533 7.85999C0.196533 12.0021 3.5544 15.36 7.69653 15.36C11.8387 15.36 15.1965 12.0021 15.1965 7.85999Z" fill="currentColor" fill-opacity="0.1"/>
              <path d="M10.9295 4.88618C11.1083 4.67577 11.4238 4.65019 11.6343 4.82904C11.8446 5.00788 11.8702 5.32343 11.6914 5.53383L7.44139 10.5338C7.25974 10.7475 6.93787 10.77 6.72825 10.5837L4.47825 8.5837C4.27186 8.40024 4.25327 8.0842 4.43673 7.87781C4.62019 7.67142 4.93622 7.65283 5.14261 7.83629L7.01053 9.49669L10.9295 4.88618Z" fill="currentColor"/>
            </svg>
            

            <span class="text-sm sm:text-base text-gray-500">
              <span class="font-bold">Less routine</span> – more creativity
            </span>
          </li>

          <li class="flex space-x-3">
            
            <svg class="flex-shrink-0 h-6 w-6 text-purple-600 dark:text-blue-500" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M15.1965 7.85999C15.1965 3.71785 11.8387 0.359985 7.69653 0.359985C3.5544 0.359985 0.196533 3.71785 0.196533 7.85999C0.196533 12.0021 3.5544 15.36 7.69653 15.36C11.8387 15.36 15.1965 12.0021 15.1965 7.85999Z" fill="currentColor" fill-opacity="0.1"/>
              <path d="M10.9295 4.88618C11.1083 4.67577 11.4238 4.65019 11.6343 4.82904C11.8446 5.00788 11.8702 5.32343 11.6914 5.53383L7.44139 10.5338C7.25974 10.7475 6.93787 10.77 6.72825 10.5837L4.47825 8.5837C4.27186 8.40024 4.25327 8.0842 4.43673 7.87781C4.62019 7.67142 4.93622 7.65283 5.14261 7.83629L7.01053 9.49669L10.9295 4.88618Z" fill="currentColor"/>
            </svg>
           

            <span class="text-sm sm:text-base text-gray-500">
              Hundreds of thousands saved
            </span>
          </li>

          <li class="flex space-x-3">
            
            <svg class="flex-shrink-0 h-6 w-6 text-purple-600 dark:text-blue-500" width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
              <path d="M15.1965 7.85999C15.1965 3.71785 11.8387 0.359985 7.69653 0.359985C3.5544 0.359985 0.196533 3.71785 0.196533 7.85999C0.196533 12.0021 3.5544 15.36 7.69653 15.36C11.8387 15.36 15.1965 12.0021 15.1965 7.85999Z" fill="currentColor" fill-opacity="0.1"/>
              <path d="M10.9295 4.88618C11.1083 4.67577 11.4238 4.65019 11.6343 4.82904C11.8446 5.00788 11.8702 5.32343 11.6914 5.53383L7.44139 10.5338C7.25974 10.7475 6.93787 10.77 6.72825 10.5837L4.47825 8.5837C4.27186 8.40024 4.25327 8.0842 4.43673 7.87781C4.62019 7.67142 4.93622 7.65283 5.14261 7.83629L7.01053 9.49669L10.9295 4.88618Z" fill="currentColor"/>
            </svg>
            

            <span class="text-sm sm:text-base text-gray-500">
              Scale budgets <span class="font-bold">efficiently</span>
            </span>
          </li>
        </ul>
      
      </div>
    </div>
   
  </div>

</div>
       </section>
       <section className='h-[100vh] w-[100%] bg-black text-white flex items-center justify-center'>
         
         <div className='flex flex-row'>
          <h3 className='font-sans font-normal text-[2rem]'>We help</h3>
         <div className='font-sans flex flex-row justify-start h-[3rem] w-[10rem] font-normal text-[2rem]  relative overflow-hidden'>
          < motion.div 
          initial={{y: '0rem'}}
          animate={{y: ['0rem','-3rem', '-6rem']}}
          transition={{duration: 2.5, delay: 2, repeat: Infinity}}
          className='grid grid-rows-3 ml-[0.4rem] absolute '>
            <h3>Brands</h3>
            <h3>Startups</h3>
            <h3>Individuals</h3>

          </motion.div>
          </div>
          </div>
         <dotlottie-player
  autoplay
  loop
  mode="normal"
  src="load1.lottie"
  style={{ height: '100%', width: '3rem' }}
 
>
</dotlottie-player>
       </section>
       <Section3 />
       <Section4 />
       <Section5 />
       <Footer />
       {/* <div class="h-[100vh] border bg-gray-100 ">
       
  <section className=" bg-black">
    <div className=" h-[100%] bg-[#1652f0] text-white z-0 sticky top-0 uppercase">
      <div className='h-[100%] w-[100%] relative'>
      <img src='background.gif' className=' w-[100%] absolute z-2' />
      <div className='h-[100%] w-[100%] bg-[#00000070] absolute z-4'></div>
      </div>
     
    </div>
    <div class="z-3 relative ">
      <h1 className='font-sans font-bold text-[4rem] my-[4rem] text-white'>Beekreed gency is the goat</h1>
      <h1 className='font-sans font-bold text-[4rem] my-[4rem] text-white'>Beekreed gency is the goat</h1>
      <h1 className='font-sans font-bold text-[4rem] my-[4rem] text-white'>Beekreed gency is the goat</h1>
      <h1 className='font-sans font-bold text-[4rem] my-[4rem] text-white'>Beekreed gency is the goat</h1>
      <h1 className='font-sans font-bold text-[4rem] my-[4rem] text-white'>Beekreed gency is the goat</h1>
      <h1 className='font-sans font-bold text-[4rem] my-[4rem] text-white'>Beekreed gency is the goat</h1>
    </div>
  </section>
  
    
</div> */}

      </main>
    </>
  )
}
